config/routes.rb
Rails.application.routes.draw do
  resources :messages

  #Error when trying the get users line so went back to resources :users
  resources :users
  #get '/users' => 'users#index'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
  
  namespace :admin do
    resources :users
    resources :messages
    get '/login' => 'logins#new', as: 'logins'
    post 'login' => 'logins#create'
    delete '/login' => 'logins#destroy'
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  
#TODO KAS Figure out how to have a user create a message
  validates :user_id, presence: true
  validates :text, presence: true
  validates_length_of :text, :maximum => 400
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  
  load_and_authorize_resource

  before_action :require_login
  before_action :authorize?
  
  def index
    @messages = Message.all
  end

  def create
    @message = message.new(message_params)
  if @message.save
    redirect_to admin_message_path(@message), notice: "message #{@message.id} was created"
  else
    render 'new'
    end
  end

  def show
   @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end 

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
  if @message.update(message_params)
    redirect_to admin_messages_path(@message), notice: "message #{@message.messagename} was updated successfully"
  else
    render 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to admin_messages_path, notice: "message #{@message.id} was deleted}"
  end

  def require_login
    unless logged_in?
      redirect_to admin_login_path, danger: 'Please log in to continue'
    end
  end

  def logged_in?
    session[:user_id].present?
  end

 private

  def message_params
    params.require(:message).permit(:text, :user_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :text)

    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to message.id, message_path(message) %></td>
        <td><%= message.user_id %></td>
        <td><%= message.text %></td>
        <td><%=l message.created_at %></td>
        <td>
          <% if can? :manage, message %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_message_path(message), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        message_path(message),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-primary' %>
<% end %>