config/routes.rb
Rails.application.routes.draw do
  resources :messages

  #Error when trying the get users line so went back to resources :users
  resources :users
  #get '/users' => 'users#index'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
  
  namespace :admin do
    resources :users
    resources :messages
    get '/login' => 'logins#new', as: 'logins'
    post 'login' => 'logins#create'
    delete '/login' => 'logins#destroy'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      render :layout => 'welcome'
  end
end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Lamppost</a>
        </div>
        <div class="navbar-collapse collapse">
          <%= form_tag admin_logins_path, class: "navbar-form navbar-right", role: 'form' do %>
            <div class="form-group">
            <%= email_field_tag :email, params[:email], placeholder: 'Email', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= password_field_tag :password, nil, placeholder: 'Password', class: 'form-control' %>
            </div>
              <%= submit_tag "Log In", class: 'btn btn-success' %>
          </form>
        </div><!--/.navbar-collapse -->
        <% end %>
      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Post a flyer on Lamppost!</h1>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Messages</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a><%= link_to ("View Messages &raquo;").html_safe, messages_path, class: "btn btn-default", role: "button" %></a></p>
        </div>
        <div class="col-md-4">
          <h2>Users</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a><%= link_to ("View Users &raquo;").html_safe, users_path, class: "btn btn-default", role: "button" %></a></p>
       </div>
        <div class="col-md-4">
          <h2>About</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">About &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>