config/routes.rb
Rails.application.routes.draw do
  resources :messages

  #Error when trying the get users line so went back to resources :users
  resources :users
  #get '/users' => 'users#index'

  # You can have the root of your site routed with "root"
  root 'welcome#index'
  
  namespace :admin do
    resources :users
    resources :messages
    get '/login' => 'logins#new', as: 'logins'
    post 'login' => 'logins#create'
    delete '/login' => 'logins#destroy'
  end
end

app/views/layouts/admin.html.erb
admin.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lamppost</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Lamppost", root_path, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Messages", messages_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Admin Log In", admin_login_path, method: "new" %></li>
          <li><%= link_to "Admin Sign out", admin_login_path, method: "delete" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
    <div class="span3">
  <h2>About Us</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lamppost</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<%= yield %></div>